# Generated by Django 4.1.7 on 2023-04-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='No_of_likes',
            new_name='no_of_likes',
        ),
    ]
